language: php

sudo: false

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini || true

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpspec run -fpretty --verbose
    - composer analyse

